### ISSUE TITLE
Fix NoClassDefFoundError: org/openqa/selenium/WebDriver

### ISSUE THREAD

**Issue by petrych** [petrych/screenshot-service#8]
MacBook-Pro:screenshot-service anastasiia$ mvn thorntail:run
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Screenshot Service 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> thorntail-maven-plugin:2.3.0.Final:run (default-cli) > package @ screenshot-service >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ screenshot-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/anastasiia/repos/public/screenshot-service/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ screenshot-service ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /Users/anastasiia/repos/public/screenshot-service/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ screenshot-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/anastasiia/repos/public/screenshot-service/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ screenshot-service ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/anastasiia/repos/public/screenshot-service/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ screenshot-service ---
[INFO] Surefire report directory: /Users/anastasiia/repos/public/screenshot-service/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.petrych.service.UtilTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-war-plugin:2.2:war (default-war) @ screenshot-service ---
[INFO] Packaging webapp
[INFO] Assembling webapp [screenshot-service] in [/Users/anastasiia/repos/public/screenshot-service/target/restful-endpoint]
[INFO] Processing war project
[INFO] Webapp assembled in [322 msecs]
[INFO] Building war: /Users/anastasiia/repos/public/screenshot-service/target/restful-endpoint.war
[INFO] 
[INFO] --- thorntail-maven-plugin:2.3.0.Final:package (default) @ screenshot-service ---
Resolving 119 out of 300 artifacts
[INFO] Repackaging .war: /Users/anastasiia/repos/public/screenshot-service/target/restful-endpoint.war
[INFO] Repackaged .war: /Users/anastasiia/repos/public/screenshot-service/target/restful-endpoint.war
[INFO] 
[INFO] <<< thorntail-maven-plugin:2.3.0.Final:run (default-cli) < package @ screenshot-service <<<
[INFO] 
[INFO] --- thorntail-maven-plugin:2.3.0.Final:run (default-cli) @ screenshot-service ---
[INFO] Starting .war
Mon Jul 08 12:48:14 CEST 2019 INFO [org.wildfly.swarm.bootstrap] (main) Dependencies not bundled; resolving from M2REPO.
2019-07-08 12:48:17,922 INFO  [org.wildfly.swarm] (main) THORN0013: Installed fraction:                   JAX-RS - STABLE          io.thorntail:jaxrs:2.3.0.Final
2019-07-08 12:48:27,943 INFO  [org.wildfly.swarm] (main) THORN0013: Installed fraction:                  Logging - STABLE          io.thorntail:logging:2.3.0.Final
2019-07-08 12:48:27,943 INFO  [org.wildfly.swarm] (main) THORN0013: Installed fraction:                 Undertow - STABLE          io.thorntail:undertow:2.3.0.Final
2019-07-08 12:48:27,944 INFO  [org.wildfly.swarm] (main) THORN0013: Installed fraction:                  Elytron - STABLE          io.thorntail:elytron:2.3.0.Final
2019-07-08 12:48:34,654 INFO  [org.jboss.msc] (main) JBoss MSC version 1.4.5.Final
2019-07-08 12:48:34,662 INFO  [org.jboss.threads] (main) JBoss Threads version 2.3.2.Final
2019-07-08 12:48:34,773 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: Thorntail 2.3.0.Final (WildFly Core 7.0.0.Final) starting
2019-07-08 12:48:34,902 INFO  [org.wildfly.swarm] (MSC service thread 1-2) THORN0019: Install MSC service for command line args: []
2019-07-08 12:48:35,384 INFO  [org.wildfly.security] (ServerService Thread Pool -- 5) ELY00001: WildFly Elytron version 1.7.0.Final
2019-07-08 12:48:35,532 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 12) WFLYNAM0001: Activating Naming Subsystem
2019-07-08 12:48:35,540 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 18) WFLYSEC0002: Activating Security Subsystem
2019-07-08 12:48:35,543 INFO  [org.xnio] (ServerService Thread Pool -- 11) XNIO version 3.6.5.Final
2019-07-08 12:48:35,549 INFO  [org.jboss.as.security] (MSC service thread 1-6) WFLYSEC0001: Current PicketBox version=5.0.3.Final
2019-07-08 12:48:35,559 INFO  [org.xnio.nio] (ServerService Thread Pool -- 11) XNIO NIO Implementation Version 3.6.5.Final
2019-07-08 12:48:35,560 INFO  [org.jboss.as.jaxrs] (ServerService Thread Pool -- 16) WFLYRS0016: RESTEasy version 3.6.2.Final
2019-07-08 12:48:35,565 INFO  [org.jboss.as.naming] (MSC service thread 1-3) WFLYNAM0003: Starting Naming Service
2019-07-08 12:48:35,574 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0003: Undertow 2.0.15.Final starting
2019-07-08 12:48:35,607 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 11) WFLYIO001: Worker 'default' has auto-configured to 16 core threads with 128 task threads based on your 8 available processors
2019-07-08 12:48:35,650 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0012: Started server default-server.
2019-07-08 12:48:35,700 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0006: Undertow HTTP listener default listening on [0:0:0:0:0:0:0:0]:8080
2019-07-08 12:48:35,751 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
2019-07-08 12:48:35,752 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Thorntail 2.3.0.Final (WildFly Core 7.0.0.Final) started in 6152ms - Started 99 of 105 services (18 services are lazy, passive or on-demand)
2019-07-08 12:48:37,373 INFO  [org.wildfly.swarm.runtime.deployer] (main) deploying restful-endpoint.war
2019-07-08 12:48:37,395 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0027: Starting deployment of "restful-endpoint.war" (runtime-name: "restful-endpoint.war")
2019-07-08 12:48:40,700 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry xml-apis.jar in /content/restful-endpoint.war/WEB-INF/lib/serializer-2.7.2.jar  does not point to a valid jar for a Class-Path reference.
2019-07-08 12:48:40,711 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry xercesImpl.jar in /content/restful-endpoint.war/WEB-INF/lib/xalan-2.7.2.jar  does not point to a valid jar for a Class-Path reference.
2019-07-08 12:48:40,712 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry xml-apis.jar in /content/restful-endpoint.war/WEB-INF/lib/xalan-2.7.2.jar  does not point to a valid jar for a Class-Path reference.
2019-07-08 12:48:40,712 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry serializer.jar in /content/restful-endpoint.war/WEB-INF/lib/xalan-2.7.2.jar  does not point to a valid jar for a Class-Path reference.
2019-07-08 12:48:41,293 WARN  [org.jboss.as.ee] (MSC service thread 1-1) WFLYEE0007: Not installing optional component org.seleniumhq.jetty9.servlets.GzipFilter$FinishOnCompleteListener due to an exception (enable DEBUG log level to see the cause)
2019-07-08 12:48:41,295 WARN  [org.jboss.as.ee] (MSC service thread 1-1) WFLYEE0007: Not installing optional component org.seleniumhq.jetty9.servlets.gzip.GzipHandler$1 due to an exception (enable DEBUG log level to see the cause)
2019-07-08 12:48:41,295 WARN  [org.jboss.as.ee] (MSC service thread 1-1) WFLYEE0007: Not installing optional component org.seleniumhq.jetty9.servlets.DoSFilter$DoSAsyncListener due to an exception (enable DEBUG log level to see the cause)
2019-07-08 12:48:41,296 WARN  [org.jboss.as.ee] (MSC service thread 1-1) WFLYEE0007: Not installing optional component org.seleniumhq.jetty9.continuation.Servlet3Continuation due to an exception (enable DEBUG log level to see the cause)
2019-07-08 12:48:41,296 WARN  [org.jboss.as.ee] (MSC service thread 1-1) WFLYEE0007: Not installing optional component org.seleniumhq.jetty9.server.handler.RequestLogHandler$1 due to an exception (enable DEBUG log level to see the cause)
2019-07-08 12:48:41,296 WARN  [org.jboss.as.ee] (MSC service thread 1-1) WFLYEE0007: Not installing optional component org.seleniumhq.jetty9.servlets.DoSFilter$DoSTimeoutAsyncListener due to an exception (enable DEBUG log level to see the cause)
2019-07-08 12:48:41,296 WARN  [org.jboss.as.ee] (MSC service thread 1-1) WFLYEE0007: Not installing optional component org.seleniumhq.jetty9.server.handler.StatisticsHandler$1 due to an exception (enable DEBUG log level to see the cause)
2019-07-08 12:48:41,296 WARN  [org.jboss.as.ee] (MSC service thread 1-1) WFLYEE0007: Not installing optional component org.seleniumhq.jetty9.server.AsyncContextState$1 due to an exception (enable DEBUG log level to see the cause)
2019-07-08 12:48:41,297 WARN  [org.jboss.as.ee] (MSC service thread 1-1) WFLYEE0007: Not installing optional component org.seleniumhq.jetty9.servlets.QoSFilter$QoSAsyncListener due to an exception (enable DEBUG log level to see the cause)
2019-07-08 12:48:41,297 WARN  [org.jboss.as.ee] (MSC service thread 1-1) WFLYEE0007: Not installing optional component org.seleniumhq.jetty9.server.handler.IdleTimeoutHandler$1 due to an exception (enable DEBUG log level to see the cause)
2019-07-08 12:48:41,356 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0018: Host default-host starting
2019-07-08 12:48:41,562 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 6) RESTEASY002225: Deploying javax.ws.rs.core.Application: class com.petrych.service.Main
2019-07-08 12:48:41,594 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 6) WFLYUT0021: Registered web context: '/' for server 'default-server'
2019-07-08 12:48:41,637 INFO  [org.jboss.as.server] (main) WFLYSRV0010: Deployed "restful-endpoint.war" (runtime-name : "restful-endpoint.war")
2019-07-08 12:48:41,646 INFO  [org.wildfly.swarm] (main) THORN99999: Thorntail is Ready
2019-07-08 12:49:30,138 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /screenshots/1: org.jboss.resteasy.spi.UnhandledException: java.lang.NoClassDefFoundError: org/openqa/selenium/WebDriver
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:78)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:222)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:193)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:455)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
        at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:61)
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1349)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/WebDriver
        at com.petrych.service.ScreenshotResource.getScreenshot(ScreenshotResource.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:509)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:399)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:363)
        at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:365)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:337)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:137)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:100)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:439)
        ... 50 more
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.WebDriver from [Module "deployment.restful-endpoint.war" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        ... 65 more

^CMacBook-Pro:screenshot-service anastasiia$ ^C
MacBook-Pro:screenshot-service anastasiia$

**Comment by petrych** [comment]
Cause: Selenium API dependency wasn't in compliance with Selenium Server and Selenium Chrome Driver dependencies.

**Solution**: have all Selenium dependencies of the same version.
